### ISSUE TITLE
[BUG][1.1.0] Places all small entities insteod of just pipes

### ISSUE THREAD

**Issue by ZwerOxotnik** [sparr/factorio-mod-automatic-underground-pipe-connectors#6]
Game version: 1.1.87
Mod version: 1.1.0

I tried in /editor and without it to place inserts, splitters, belts, chests etc., but the mod placed second one near it.

**Comment by ZwerOxotnik** [comment]
I'll send a save file in several minutes, because I can't reproduce it in other games.

**Comment by ZwerOxotnik** [comment]
Save file: [big__pipe_mod.zip](https://github.com/sparr/factorio-mod-automatic-underground-pipe-connectors/files/12206620/big__pipe_mod.zip)

**Comment by ZwerOxotnik** [comment]
huh, now it happens only in editor mode.

**Comment by sparr** [comment]
I haven't been able to reproduce this. Please comment here if you encounter this behavior again.
